### ISSUE TITLE
[Bug] Hráčův kolizní tvar

### ISSUE THREAD

**Issue by manakmar** [Bumares/Point-of-view#1]
**Godot Version & Plugin Version**
Godot: *3.2.3*

**Describe the bug**
Změňte kolizní tvar z "rectangle" na "capsule". Zdá se, že funkce move_and_slide má s obdélníkem problém - hráč se mi při pohybu doprava zasekává.

**Comment by Bumares** [comment]
Opraveno, změna kolizního tvaru problém vyřešila.
